default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres
  password: 123
  database: Matching

development:
  <<: *default
  #database: db/development.sqlite3


test:
  <<: *default
  #database: db/test.sqlite3

production:
  <<: *default
