# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

d1=Device.create(title: 'Raptor Reloaded')
d2=Device.create(title: 'Phoenix')
d3=Device.create(title: 'UnLimbited Arm')
d4=Device.create(title: 'Python')

m1=Member.create(first_name: 'Joe', last_name: 'C', email: 'joecross@gmail.com', city: 'San Diego', country: 'USA', password: '123456', password_confirmation: '123456', admin: true)
m2=Member.create(first_name: 'Amanda', last_name: 'J', email: 'joecross.2@gmail.com', city: 'San Diego', country: 'USA', password: '123456', password_confirmation: '123456')
m3=Member.create(first_name: 'Maker1', last_name: 'J', email: 'joecross.3@gmail.com', city: 'San Diego', country: 'USA', password: '123456', password_confirmation: '123456')
m10=Member.create(first_name: 'Maker2', last_name: 'J', email: 'joecross.10@gmail.com', city: 'San Diego', country: 'USA', password: '123456', password_confirmation: '123456')
m4=Member.create(first_name: 'Recipient1', last_name: 'T', email: 'joecross.4@gmail.com', city: 'Budapest', country: 'Hungary', password: '123456', password_confirmation: '123456')
m5=Member.create(first_name: 'Recipient2', last_name: 'T', email: 'joecross.5@gmail.com', city: 'San Diego', country: 'USA', password: '123456', password_confirmation: '123456')
m6=Member.create(first_name: 'Recipient3', last_name: 'T', email: 'joecross.6@gmail.com', city: 'San Diego', country: 'USA', password: '123456', password_confirmation: '123456')
m7=Member.create(first_name: 'Recipient4', last_name: 'T', email: 'joecross.7@gmail.com', city: 'San Diego', country: 'USA', password: '123456', password_confirmation: '123456')
m8=Member.create(first_name: 'Recipient5', last_name: 'T', email: 'joecross.8@gmail.com', city: 'San Diego', country: 'USA', password: '123456', password_confirmation: '123456')
m9=Member.create(first_name: 'Recipient6', last_name: 'T', email: 'joecross.9@gmail.com', city: 'San Diego', country: 'USA', password: '123456', password_confirmation: '123456')


r1=Request.create(member_id: m1.id, device_id: d2.id, side: 'Left', stage: 'Open', shipping_address: 'San Diego, USA')
r2=Request.create(member_id: m5.id, device_id: d3.id, side: 'Right', stage: 'Open', shipping_address: 'Budapest, Hungary')
r3=Request.create(member_id: m6.id, device_id: d2.id, side: 'Left', stage: 'Matched', shipping_address: 'Los Angeles, USA')
r4=Request.create(member_id: m7.id, device_id: d4.id, side: 'Left', stage: 'Completed', shipping_address: '1351 La Mancha Pl\nChula Vista, CA, 91910\nUSA')
r5=Request.create(member_id: m8.id, device_id: d4.id, side: 'Left', stage: 'Completed', shipping_address: 'London, England')
r6=Request.create(member_id: m9.id, device_id: d4.id, side: 'Right', stage: 'Open', shipping_address: 'San Francisco, CA')
r7=Request.create(member_id: m9.id, device_id: d4.id, side: 'Left', stage: 'Completed', shipping_address: '612 First St, Miami, CA, 92109')
r8=Request.create(member_id: m4.id, device_id: d2.id, side: 'Left', stage: 'Matched', shipping_address: 'San Diego, USA')
r9=Request.create(member_id: m4.id, device_id: d2.id, side: 'Right', stage: 'Matched', shipping_address: 'Dallas, TX')
r10=Request.create(member_id: m6.id, device_id: d4.id, side: 'Left', stage: 'Completed', shipping_address: 'San Diego, USA')
r11=Request.create(member_id: m6.id, device_id: d4.id, side: 'Left', stage: 'Completed', shipping_address: 'Madrid, Spain')
r12=Request.create(member_id: m6.id, device_id: d4.id, side: 'Left', stage: 'Completed', shipping_address: 'Accra, Ghana')

o1=Offer.create(request_id: r1.id, member_id: m3.id, stage: 'Offered')
o2=Offer.create(request_id: r3.id, member_id: m3.id, stage: 'Accepted')
o3=Offer.create(request_id: r1.id, member_id: m10.id, stage: 'Declined')
o4=Offer.create(request_id: r4.id, member_id: m1.id, stage: 'Abandoned')
o5=Offer.create(request_id: r8.id, member_id: m10.id, stage: 'Accepted')
o6=Offer.create(request_id: r9.id, member_id: m1.id, stage: 'Accepted')
o7=Offer.create(request_id: r4.id, member_id: m2.id, stage: 'Accepted')
o8=Offer.create(request_id: r5.id, member_id: m1.id, stage: 'Accepted')
o9=Offer.create(request_id: r10.id, member_id: m10.id, stage: 'Declined')
o12=Offer.create(request_id: r10.id, member_id: m9.id, stage: 'Declined')
o10=Offer.create(request_id: r11.id, member_id: m10.id, stage: 'Declined')
o11=Offer.create(request_id: r12.id, member_id: m10.id, stage: 'Declined')

ch1=Chapter.create(name: 'El Jardín Digital', active: true, email: 'eljardindigital@gmail.com', location: 'Madrid, Spain', intake: 'None', home: 'https://www.facebook.com/eljardindigital3d/', donation: 'None')
ch2=Chapter.create(name: 'LIMBITLESS – UCF', active: true, email: 'contact@limbitless-solutions.org', location: 'University of Central Florida, FL, USA', intake: 'http://limbitless-solutions.org/index.php/contact/', home: 'http://limbitless-solutions.org/', donation: 'http://limbitless-solutions.org/index.php/donate2/')
ch3=Chapter.create(name: 'Not Impossible', active: true, email: 'People@NotImpossibleNow.com', location: 'Sudan', intake: 'None', home: 'http://www.notimpossiblenow.com/labs/project-daniel', donation: 'None')
ch4=Chapter.create(name: 'Po Paraguay', active: true, email: 'fvallese@po.com.py', location: 'Asuncion, Paraguay', intake: 'http://www.po.com.py/#homepage-block-5', home: 'http://www.po.com.py/', donation: 'https://www.generosity.com/community-fundraising/po-3d-printing-prosthetics-with-attitude')
ch5=Chapter.create(name: 'PROHAND3D CHILE', active: true, email: '', location: 'Chile', intake: 'None', home: 'https://www.facebook.com/ProHand3D', donation: 'https://www.paypal.com/al/cgi-bin/webscr?cmd=_flow&SESSION=yHPVJpurgcrr8EwycGjtIyFgl3v29mK7kfcyOA9aU9_Fa3xGZJXwva92dUq&dispatch=5885d80a13c0db1f8e263663d3faee8dcce3e160f5b9538489e17951d2c62172')
ch6=Chapter.create(name: 'e-NABLE Turkey / Robotel Türkiye', active: true, email: 'zeynep@5dakika.com, temizert@gmail.com', location: 'Instabul, Turkey', intake: 'http://www.robotel.org/?page_id=3685', home: 'http://www.robotel.org/', donation: 'None')
ch7=Chapter.create(name: 'Team UnLimbited UK', active: true, email: 'hello@teamunlimbited.org', location: 'England', intake: 'http://www.teamunlimbited.org/contact/', home: 'http://www.teamunlimbited.org/', donation: 'https://secure.squarespace.com/commerce/donate?donatePageId=55c484fae4b0a45eb98717b7')
ch8=Chapter.create(name: 'e-NABLE Nigeria / CyberLogik Foundation', active: true, email: 'cyberlogikfoundation@gmail.com', location: 'Nigeria', intake: 'http://goo.gl/forms/GrIOgeqvny', home: 'https://www.facebook.com/Cyberlogik-Foundation-182196985172683/', donation: 'https://www.generosity.com/volunteer-fundraising/free-3d-printed-prosthetic-hands-in-africa')
ch9=Chapter.create(name: 'e-NABLE België', active: true, email: '', location: 'Belgium', intake: 'None', home: 'https://www.facebook.com/E-Nable-België-1126279240729066/', donation: 'None')
ch10=Chapter.create(name: 'e-NABLE Colombia', active: true, email: '', location: 'Bogota, Colombia', intake: '', home: '', donation: '')
ch11=Chapter.create(name: 'e-NABLE Egypt', active: true, email: 'Omar_Abdelaal@student.uml.edu', location: 'Cairo, Egypt', intake: 'None', home: 'https://www.facebook.com/enablegypt/', donation: 'None')
ch12=Chapter.create(name: 'e-NABLE France', active: true, email: 'theo@e-nable.fr', location: 'France', intake: 'http://e-nable.fr/?page_id=259', home: 'http://e-nable.fr/', donation: 'https://e-nable.fr/?page_id=155')
ch13=Chapter.create(name: 'e-NABLE Ghana', active: true, email: 'enableinghana@gmail.com', location: 'Accra, Ghana', intake: 'http://goo.gl/forms/GrIOgeqvny', home: 'https://www.facebook.com/enableinghana', donation: 'https://www.generosity.com/volunteer-fundraising/free-3d-printed-prosthetic-hands-in-ghana/')
ch14=Chapter.create(name: 'e-NABLE HONG KONG', active: true, email: '', location: 'Hong Kong', intake: 'None', home: 'https://www.facebook.com/profile.php?id=100009996738507', donation: 'None')
ch15=Chapter.create(name: 'e-NABLE Magyarország', active: true, email: 'joe@enable.hu', location: 'Budapest, Hungary', intake: 'http://goo.gl/forms/SXpS6xwyzA', home: 'http://enable.hu/', donation: 'https://www.generosity.com/volunteer-fundraising/prosthetic-arms-for-kids-in-hungary')
ch16=Chapter.create(name: 'e-NABLE Melbourne', active: true, email: 'chris@enablemelbourne.org', location: 'Melbourne VIC, Australia', intake: 'None', home: 'https://www.facebook.com/enableMelbourne/', donation: 'None')
ch17=Chapter.create(name: 'e-NABLE MEXICO', active: true, email: '', location: 'Mexico', intake: 'None', home: 'https://www.facebook.com/enableMX', donation: 'None')
ch18=Chapter.create(name: 'e-NABLE Rochester', active: true, email: 'david@limblab.com', location: 'Rochester, MN', intake: 'None', home: 'https://www.facebook.com/groups/enablerochester/?fref=nf', donation: 'None')
ch19=Chapter.create(name: 'e-NABLE TAIWAN', active: true, email: '', location: 'Taiwan', intake: 'None', home: 'https://www.facebook.com/enabletaiwan', donation: 'None')
ch20=Chapter.create(name: 'e-NABLE THAILAND', active: true, email: '', location: 'Thailand', intake: 'None', home: 'https://www.facebook.com/enableorganizationthailand', donation: 'None')
ch21=Chapter.create(name: 'e-NABLE VENEZUELA', active: true, email: '', location: 'Venezuela', intake: 'None', home: 'https://www.facebook.com/E-NableVenezuela-431087203758874/', donation: 'None')
ch22=Chapter.create(name: 'Bucknell University (Pennsylvania)', active: true, email: 'elp015@bucknell.edu', location: 'Bucknell University, PA', intake: 'None', home: 'https://www.facebook.com/enableatbucknell/', donation: 'None')
ch23=Chapter.create(name: 'e-NABLE CCNY', active: true, email: '', location: 'City College of New York, New York, NY, USA', intake: 'None', home: 'https://www.facebook.com/eNABLEatCCNY/', donation: 'None')
ch24=Chapter.create(name: 'e-NABLE Trinity College', active: true, email: 'marissa.stein@trincoll.edu', location: 'Hartford, CT, USA', intake: '', home: '', donation: '')
ch25=Chapter.create(name: 'e-NABLE Umass Lowell', active: true, email: 'enablelowell@gmail.com', location: 'Lowell, Massachusetts', intake: 'None', home: 'https://www.facebook.com/enablelowell/', donation: 'None')
ch26=Chapter.create(name: 'HAND CHALLENGE – SC', active: true, email: 'info@handchallenge.com', location: 'Irmo, Columbia, SC, USA', intake: 'http://www.handchallenge.com/sign-up.html', home: 'http://www.handchallenge.com/', donation: 'None')
ch27=Chapter.create(name: 'HELPING HAND PROJECT – NC', active: true, email: '', location: 'University of North Carolina, Chapel Hill, NC, USA', intake: 'http://www.helpinghandproject.org/get-a-device-for-your-child.html', home: 'http://www.helpinghandproject.org/', donation: 'http://www.helpinghandproject.org/donate.html')
ch28=Chapter.create(name: 'Marymount University in Arlington VA', active: true, email: '', location: 'Marymount University, Arlington, VA', intake: 'None', home: 'https://www.facebook.com/enablemarymount/', donation: 'None')
ch29=Chapter.create(name: 'University of Florida', active: true, email: 'jessicabergau1@gmail.com', location: 'University of Florida, FL, USA', intake: '', home: '', donation: '')
ch30=Chapter.create(name: 'e-NABLE New Caledonia', active: true, email: 'jc.turcon@enable.asso.nc', location: 'New Caledonia', intake: '', home: 'https://www.facebook.com/enable.asso.nc/', donation: 'http://enable.asso.nc/dons.html')
ch31=Chapter.create(name: 'e-NABLE Harbin / Touch the Future', active: true, email: 'guancheng.lai.aiesec@outlook.com', location: 'Harbin, Heilongjiang, China', intake: '', home: 'http://weibo.com/5992679099/profile?topnav=1&wvr=6', donation: 'http://gongyi.qq.com/succor/detail.htm?id=14033')
ch32=Chapter.create(name: 'e-NABLE Weston', active: true, email: 'jbargamian@meadowbrook-ma.org', location: 'Meadowbrook School of Weston, Weston, Massachusetts', intake: 'https://docs.google.com/a/meadowbrook-ma.org/forms/d/1J6viq6wj6bmEc4y6d-HY5V5uzPXX6NqPrdM2bzx5jl0/viewform', home: 'http://meadowbrookhands.wix.com/meadowbrookhands', donation: 'None')
ch33=Chapter.create(name: 'e-NABLE UH', active: true, email: 'jyazji@uh.edu', location: 'University of Houston, Houston, Texas, USA', intake: 'https://uh.collegiatelink.net/organization/enable_uh', home: 'https://www.facebook.com/enableuh/', donation: '')
ch34=Chapter.create(name: 'e-NABLE Honduras', active: true, email: 'k3d.honduras@gmail.com', location: 'Tegucigalpa, Honduras ', intake: '', home: 'www.facebook.com/kids3d.hand', donation: '')
ch35=Chapter.create(name: 'El Dorado Hills Library', active: true, email: 'gsself@gmail.com', location: 'El Dorado Hills, California, USA', intake: '', home: 'https://sites.google.com/site/eldoradohillslibrary3dprintlab/', donation: '')
ch36=Chapter.create(name: 'e-NABLE Pakistan', active: true, email: 'asadjabbar11@gmail.com', location: 'Karachi, Pakistan', intake: '', home: 'https://www.facebook.com/grit3d', donation: '')
ch37=Chapter.create(name: 'Haifa3D', active: true, email: 'yair.herbst@gmail.com', location: 'Haifa, Israel', intake: '', home: 'http://haifa3D.org', donation: '')
ch38=Chapter.create(name: 'e-NABLE FORRFS', active: true, email: 'dvial@volcano.net', location: 'Rail Road Flat, CA, USA', intake: '', home: 'www.friendsofrrfschool.org', donation: '')
ch39=Chapter.create(name: 'e-NABLE Germany', active: true, email: 'lasse.92@gmx.de', location: 'Duisburg, Germany', intake: 'http://www.enable-germany.de/kontakt/', home: 'https://www.facebook.com/enableGermany/', donation: '')
ch40=Chapter.create(name: 'Boise Public Library', active: true, email: 'askalibrarian@cityofboise.org', location: 'Boise, ID, USA', intake: '', home: 'https://www.facebook.com/boisepublib', donation: '')
ch41=Chapter.create(name: 'e-NABLE Kazahkstan', active: true, email: 'sistayeva@gmail.com', location: 'Astana, Kazahkstan', intake: 'http://sistayeva.wixsite.com/enablekz', home: 'https://www.facebook.com/enableNU/', donation: 'http://sistayeva.wixsite.com/enablekz')
ch42=Chapter.create(name: 'Enabling Music', active: true, email: 'enablingmusic@gmail.com', location: 'Yorba Linda, CA, USA', intake: 'https://goo.gl/forms/PDp0xMDUy9RXvCFP2', home: 'https://www.facebook.com/enablingmusic/', donation: 'https://igg.me/at/QbClRZtj-nA')
ch43=Chapter.create(name: 'e-NABLE Argentina', active: true, email: 'saicrox@gmail.com', location: 'Moreno, Buenos Aires, Argentina', intake: '', home: '', donation: '')
ch44=Chapter.create(name: 'Helping Hand Adventurers', active: true, email: 'Helpinghandadventurers@gmail.com', location: 'South Bay, California', intake: '', home: 'www.facebook.com/helpinghand.adventurers', donation: '')
ch45=Chapter.create(name: 'e-NABLE Chile / Fundación Prótesis 3D', active: true, email: 'contacto@fundacionprotesis3d.cl', location: 'Chile', intake: '', home: 'www.facebook.com/fundacionprotesis3d', donation: '')
ch46=Chapter.create(name: 'e-NABLE Canada', active: true, email: 'pbyron@e-nable.ca', location: 'Montreal, Canada', intake: '', home: 'https://www.facebook.com/enablecanada/?ref=aymt_homepage_panel', donation: '')
ch47=Chapter.create(name: 'e-NABLE Vietnam', active: true, email: 'enablingvietnam@gmail.com', location: 'Hanoi, Vietnam', intake: '', home: '', donation: '')
ch48=Chapter.create(name: 'Donate A Hand', active: true, email: 'austin@secon.com', location: 'Atlanta, Georgia, United States', intake: 'http://www.donateahand.org/request-a-hand/', home: 'http://www.donateahand.org', donation: 'http://www.donateahand.org/donate/')
ch49=Chapter.create(name: 'Guala Honduras', active: true, email: 'emanuelcruz07@gmail.com', location: 'San Pedro Sula, Honduras', intake: '', home: 'http://www.facebook.com/gualahn', donation: 'http://www.gofundme.com/by62hemk')
ch50=Chapter.create(name: 'e-NABLE Boston', active: true, email: 'tatiana.kelil3d@gmail.com', location: 'Boston, MA', intake: '', home: 'https://www.facebook.com/E-Nable-Boston-1667861066875214/?skip_nax_wizard=true', donation: '')
ch51=Chapter.create(name: 'ECPI University – Innsbrook Campus', active: true, email: 'nghochaghi@ecpi.edu', location: 'Glen Allen, Virginia', intake: '', home: '', donation: '')
ch52=Chapter.create(name: 'e-NABLE SCIL', active: true, email: 'klewis@swcil.org', location: 'Springfield, MO USA', intake: '', home: 'https://www.facebook.com/southwestcenterforindependentliving/', donation: '')
ch53=Chapter.create(name: 'e-NABLE Poland', active: true, email: 'eNablePolska@gmail.com', location: 'Kraków, Poland', intake: 'https://www.facebook.com/eNablePolska/', home: 'http://e-nable.pl/', donation: '')
ch54=Chapter.create(name: '3D Fabrication Society', active: true, email: '3dfabricationsociety@gmail.com', location: 'Brookfield Wisconsin', intake: '', home: '', donation: '')
ch55=Chapter.create(name: 'e-NABLE India', active: true, email: 'enablechapterindia@gmail.com', location: 'Goa, India', intake: 'https://docs.google.com/forms/d/16YOc9npGMnPmvB2yI6ol1-t9zoEfv6bX8qnPXK2Njzg/edit', home: 'https://www.facebook.com/E-Nable-India-192439977866359/', donation: 'http://www.e-nableindia.in/')
ch56=Chapter.create(name: 'e-NABLE Mauritius', active: true, email: 'oudaye@intnet.mu', location: 'Plaine Des Papayes, Mauritius', intake: '', home: 'https://www.facebook.com/groups/3DPrinterMauritius/', donation: '')
ch57=Chapter.create(name: 'e-NABLE Notre Dame', active: true, email: 'kpacific@nd.edu', location: 'Notre Dame, Indiana', intake: '', home: '', donation: '')
ch58=Chapter.create(name: 'Joliet Central Engineers', active: true, email: 'engineersjc@gmail.com', location: 'Joliet, Illinois, Region 7, United States', intake: '', home: 'https://www.facebook.com/Joliet-Central-Engineers-1811444479067560/?skip_nax_wizard=true', donation: '')
ch59=Chapter.create(name: 'e-NABLE Lehigh University', active: true, email: 'enablingthefuture2016@gmail.com ', location: 'Bethlehem, PA, USA', intake: '', home: '', donation: '')
ch60=Chapter.create(name: 'e-NABLE Toronto', active: true, email: 'enabletoronto@gmail.com', location: 'Toronto, Ontario, Canada', intake: '', home: 'https://www.facebook.com/enabletoronto', donation: '')
ch61=Chapter.create(name: 'e-NABLE Brazil', active: true, email: 'david.ritchie@eabh.com.br', location: 'Belo Horizonte, Minas Gerais, Brazil', intake: '', home: '', donation: '')
ch62=Chapter.create(name: 'Claws from Carter', active: true, email: 'clawsfromcarter@gmail.com', location: 'Grand Rapids, Michigan', intake: '', home: 'www.facebook.com/clawsfromcarter', donation: 'www.gofundme.com/clawsfromcarter')
ch63=Chapter.create(name: 'e-NABLE Essex', active: true, email: 'Enable@emails2me.co.uk', location: 'Romford, Essex, UK', intake: '', home: '', donation: '')
ch64=Chapter.create(name: 'e-NABLE Iowa', active: true, email: 'sedan46@aol.com', location: 'Cedar Falls, Iowa', intake: '', home: 'https://www.facebook.com/sedan46/', donation: '')
ch65=Chapter.create(name: 'e-NABLE Boca Raton', active: true, email: 'dzimmer@tech3design.com', location: 'Boca Raton, FL', intake: '', home: '', donation: '')
ch66=Chapter.create(name: 'STEM SoS', active: true, email: 'mgokcek@harmonytx.org', location: 'Sugarland, Houston, TX', intake: '', home: 'https://www.facebook.com/enableSTEMSOS', donation: '')
ch67=Chapter.create(name: 'e-NABLE Columbia', active: true, email: 'fheflin@me.com', location: 'Columbia, SC, USA', intake: '', home: '', donation: '')
ch68=Chapter.create(name: 'e-NABLE Saudi', active: true, email: 'enablesaudi@gmail.com', location: 'Jeddah, Saudi Arabia', intake: 'https://docs.google.com/forms/d/1CEr54Cm_HCqH4XQEhWtmLI6QjqeFWtUGIPtE7YGpa6U/viewform?edit_requested=true', home: 'https://www.facebook.com/enablesaudi/', donation: 'https://www.generosity.com/medical-fundraising/3d-printed-hand-for-those-in-need-in-saudi-arabia--2/x/15872311')
ch69=Chapter.create(name: 'Rupert A Nock e-NABLE', active: true, email: 'babalkus@newburyport.k12.ma.us', location: 'Newburyport, MA', intake: '', home: '', donation: '')
ch70=Chapter.create(name: 'Sacred Heart School e-NABLE ', active: true, email: 'edmartinez@sacredheartfamily.com', location: 'Lake Worth, FL', intake: '', home: 'https://www.facebook.com/shspanther/', donation: '')
ch71=Chapter.create(name: 'e-NABLE Sweden', active: true, email: 'lamin@xpandedreality.com', location: 'Stockholm, Sweden', intake: '', home: '', donation: '')
ch72=Chapter.create(name: 'e-NABLE Tunisie', active: true, email: 'bentalebomarebay@gmail.com', location: 'Tunisia', intake: '', home: 'https://www.facebook.com/ENableTunisie/', donation: '')
ch73=Chapter.create(name: 'e-NABLE Scotland', active: true, email: 'handprints.enable@gmail.com', location: 'Glasgow, Scotland', intake: '', home: 'https://www.facebook.com/handprints.enable/', donation: '')
ch74=Chapter.create(name: 'e-NABLE Medellin', active: true, email: 'social@u3d.com.co', location: 'Medellin, Colombia', intake: '', home: 'http://www.u3d.com.co/historias', donation: '')
ch75=Chapter.create(name: 'Beyond Limbits', active: true, email: 'BeyondLimbits@gmail.com', location: 'Redditch, Worcestershire, United Kingdom', intake: '', home: 'https://m.facebook.com/BeyondLimbits/', donation: '')
ch76=Chapter.create(name: 'e-NABLE Nederland', active: true, email: 'robberts.erik@gmail.com', location: 'Rotterdam, the Netherlands', intake: '', home: 'https://www.facebook.com/enablenederland/', donation: '')
ch77=Chapter.create(name: 'ASSOCIAÇÃO DAR A MÃO', active: true, email: 'geane.gaps@gmail.com ', location: 'São João do Ivaí,  Paraná,  Brazil', intake: '', home: 'www.facebook.com/associacaodaramao ', donation: '')
ch78=Chapter.create(name: 'e-NABLE Italy', active: true, email: 'handanewdream@gmail.com', location: 'Mantua, Lombardy, Italy', intake: '', home: 'https://www.facebook.com/HAND-813303878810610/', donation: '')
ch79=Chapter.create(name: 'e-NABLE Hellstern', active: true, email: 'hellsternms@eastschools.org', location: 'Springdale, AR', intake: '', home: 'https://www.facebook.com/profile.php?id=100015031657450', donation: '')
ch80=Chapter.create(name: 'e-NABLE Korea', active: true, email: 'Everlastingly.H@gmail.com', location: 'Pohang-Si, South Korea', intake: '', home: 'https://www.facebook.com/FiveFinger.org/', donation: '')
ch81=Chapter.create(name: 'East Leyden High School', active: true, email: 'hm21795@student.leyden212.org', location: 'Franklin Park, Illinois', intake: '', home: '', donation: '')
ch82=Chapter.create(name: 'Univ of San Francisco Library', active: true, email: 'beatrice.mallek@ucsf.edu', location: 'San Francisco, CA', intake: '', home: 'www.facebook.com/ucsflibrary', donation: '')
ch83=Chapter.create(name: 'e-NABLE Peru', active: true, email: 'ricardo.g.rodriguez.t@gmail.com', location: 'Piura, Perú', intake: '', home: 'https://www.facebook.com/enablePeruPIXED/', donation: '')
ch84=Chapter.create(name: 'e-NABLE Caribbean', active: true, email: 'info@inktechbb.com', location: 'St. James, Barbados', intake: '', home: 'https://www.facebook.com/enablecaribbean/', donation: '')
ch85=Chapter.create(name: 'e-NABLE Brown University Chapter', active: true, email: 'rana_ozdeslik@brown.edu', location: 'Providence, RI', intake: '', home: 'https://www.facebook.com/profile.php?id=100015104011137', donation: 'https://www.generosity.com/volunteer-fundraising/e-nable-brown-university-chapter/x/15943555')
ch86=Chapter.create(name: 'e-NABLE Nairobi', active: true, email: 'dmackrory@isk.ac.ke', location: 'Nairobi, Kenya', intake: '', home: 'https://www.facebook.com/handoutenablethefuture', donation: '')
ch87=Chapter.create(name: 'e-NABLE San Gabriel Valley', active: true, email: 'gzorko@gmail.com', location: 'San Dimas, CA', intake: '', home: 'https://www.facebook.com/enableSGV/', donation: '')